Feature/s65 150
S65-2-project/AccountService pull request #9
Opened 2020-05-11 07:50 UTC by WouterVan

2020-05-11 09:07 UTC, davydehaas98 reviewed
Let over het algemeen op de benaming van classes, test methodes en de onnodige witruimte, dat leest net wat fijner.

2020-05-11 09:07 UTC, davydehaas98 commented on AccountService/Controllers/AccountController.cs
>      [ApiController]
Zet er [Authorize] boven

2020-05-11 09:07 UTC, davydehaas98 commented on AccountService/Controllers/AccountController.cs
>          [AllowAnonymous]
Je mag niet anonymous een wachtwoord aanpassen.

2020-05-11 09:07 UTC, davydehaas98 commented on AccountService/Controllers/AccountController.cs
>          [AllowAnonymous]
Je mag niet anonymous een account aanpassen.

2020-05-11 09:07 UTC, davydehaas98 commented on AccountService/Controllers/AccountController.cs
>          [AllowAnonymous]
Je mag niet anonymous een account verwijderen.

2020-05-11 09:07 UTC, davydehaas98 commented on AccountService/Domain/Account.cs
>      public class Account
Fix de 8 spaces indentation naar 4.

2020-05-11 09:07 UTC, davydehaas98 commented on AccountService/Helpers/AppSettings.cs
> +
Onnodige whitespace

2020-05-11 09:07 UTC, davydehaas98 commented on AccountService/Helpers/ExtenstionMethods.cs
>          public static Account WithoutPassword(this Account account) {
Misschien een idee om er WithoutSensitiveData van te maken aangezien niet alleen het wachtwoord, maar ook de salt niet wordt meegestuurd.

2020-05-11 09:07 UTC, davydehaas98 commented on AccountService/Helpers/ExtenstionMethods.cs
>          public static Account WithoutPassword(this Account account) {
Misschien kunnen we er WithoutSensitiveData van maken in plaats van password omdat wij naast het wachtwoord ook de salt niet meesturen. Is wat duidelijker van wat de methode doet ipv alleen het wachtwoord zelf.

2020-05-11 09:07 UTC, davydehaas98 commented on AccountService/Helpers/RegexHelper.cs
> +                       "^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+",
Onnodige indentations van 8 spaces

2020-05-11 09:07 UTC, davydehaas98 commented on AccountService/Repositories/IAccountRepository.cs
> +        /// <returns></returns>
De return values zijn niet ingevuld

2020-05-11 09:07 UTC, davydehaas98 commented on AccountService/Services/AccountService.cs
> +            await _repository.Create(newAccount);
Pak de return value van create en stop die in newAccount. Return die waarde vervolgens zonder sensitive data ipv de account values die niet in de database zijn geweest.

2020-05-11 09:07 UTC, davydehaas98 commented on AccountService/Services/AccountService.cs
> +            await _repository.Update(account.Id, account);
Gebruik deze return value ipv opnieuw een get uit te voeren

2020-05-11 09:07 UTC, davydehaas98 commented on AccountService/Services/AccountService.cs
> +            var acc = await _repository.Get(id);
account.

2020-05-11 09:07 UTC, davydehaas98 commented on AccountService/Services/AccountService.cs
> +            var acc = await GetAccount(id);
account.

2020-05-11 09:07 UTC, davydehaas98 commented on AccountService/Services/AccountService.cs
> +            var acc = await _repository.Get(id);
account.

2020-05-11 09:07 UTC, davydehaas98 commented on AccountService/Services/AccountService.cs
> +                await _repository.Remove(id);
one liner en verwijder onnodige whitespacing

2020-05-11 09:07 UTC, davydehaas98 commented on AccountService/Services/IAccountService.cs
> +    public interface IAccountService
Vul de return xml documentation ipv dit in de summary erbij zetten als je toch het returns veld hebt aangemaakt

2020-05-11 09:07 UTC, davydehaas98 commented on AccountService/Services/IAccountService.cs
> +    public interface IAccountService
Gebruik als input of model, of de uitgeschreven class name. Niet de ene keer model en de andere keer loginModel of passwordModel wat nieteens overeenkomt met de class name

2020-05-11 09:07 UTC, davydehaas98 commented on AccountServiceTests/Controller/AccountControllerTest.cs
> +            var data = result as ObjectResult;
Zet as ObjectResult gewoon meteen achter de await ipv een losse regel wat niks toevoegd

2020-05-11 09:07 UTC, davydehaas98 commented on AccountServiceTests/Controller/AccountControllerTest.cs
> +            var encryptedPassword = Encoding.ASCII.GetBytes(password);
Die encrypted password kun je net als de salt invullen ipv een encoding te gaan aanroepen wat niet nodig is zolang je maar een new byte[] hebt

2020-05-11 09:07 UTC, davydehaas98 commented on AccountServiceTests/Repository/AccountRepositoryTest.cs
> +        public void Dispose()
Haal weg

2020-05-11 09:07 UTC, davydehaas98 commented on AccountServiceTests/Repository/AccountRepositoryTest.cs
> +                Password = Encoding.ASCII.GetBytes("MyVeryStrongTestPassword123!"),
Hier ook alle passwords naar new byte[] {0x20, 0x20, 0x20, 0x20}

2020-05-11 09:07 UTC, davydehaas98 commented on AccountServiceTests/Controller/AccountControllerTest.cs
> +        public async Task CreateAccountTest()
Houden we een naming scheme aan of niet. Als we dat willen moeten we alle methode namen naar [UnitOfWork_StateUnderTest_ExpectedBehavior] veranderen:
https://stackoverflow.com/questions/155436/unit-test-naming-best-practices

2020-05-11 09:07 UTC, davydehaas98 commented on AccountServiceTests/Controller/AccountControllerTest.cs
> +            //Act
Zet overal of wel Arrange, Act en Assert comments neer of niet. Niet half

2020-05-11 09:07 UTC, davydehaas98 commented on AccountServiceTests/Repository/AccountRepositoryTest.cs
> +           [Fact]
Indentation

2020-05-11 09:07 UTC, davydehaas98 commented on AccountServiceTests/ServiceTests/AccountServiceTest.cs
> +
Whitespacing

2020-05-11 09:07 UTC, davydehaas98 commented on AccountServiceTests/ServiceTests/AccountServiceTest.cs
> +            _accountService = new AccountService.Services.AccountService(_repository.Object, _hasher.Object, _jwtGenerator.Object,
Plaats een enter na AccountService( zodat alles fatsoenlijk leesbaar is en haal hieronder de whitespacing weg

2020-05-11 09:07 UTC, davydehaas98 commented on AccountServiceTests/ServiceTests/AccountServiceTest.cs
> +
Drie is wel te veel van het goede

2020-05-11 09:07 UTC, davydehaas98 commented on AccountServiceTests/ServiceTests/AccountServiceTest.cs
> +
Witruimte

2020-05-11 09:07 UTC, davydehaas98 commented on AccountServiceTests/ServiceTests/AccountServiceTest.cs
> +
Witruimte

2020-05-11 09:07 UTC, davydehaas98 commented on AccountServiceTests/ServiceTests/AccountServiceTest.cs
> +
Witruimte

2020-05-11 09:07 UTC, davydehaas98 commented on AccountServiceTests/ServiceTests/AccountServiceTest.cs
> +namespace AccountServiceTests.ServiceTests
Geen bad flow voor controller register, login, create, get en update tests?

2020-05-11 12:13 UTC, WouterVan commented on AccountServiceTests/ServiceTests/AccountServiceTest.cs
> +namespace AccountServiceTests.ServiceTests
nope
'

2020-05-12 12:00 UTC, FlorisFeddema requested changes

2020-05-12 12:00 UTC, FlorisFeddema commented on AccountService/Controllers/AccountController.cs
> +                //TODO Custom exception aanmaken voor deze methode.
Delete deze TODO

2020-05-12 12:00 UTC, FlorisFeddema commented on AccountService/Helpers/IHasher.cs
> +﻿﻿using System.Threading.Tasks;
Commenting

2020-05-12 12:00 UTC, FlorisFeddema commented on AccountService/Helpers/ITokenGenerator.cs
> +﻿using System;
Commends

2020-05-12 12:00 UTC, FlorisFeddema commented on AccountService/Services/AccountService.cs
> +        //TODO Custom exception for every argument
TODO weghalen

2020-05-12 12:00 UTC, FlorisFeddema commented on AccountService/Startup.cs
> +            #region jwt
Geen region aub

2020-05-12 12:09 UTC, FlorisFeddema approved these changes

2020-05-12 12:09 UTC, merged